// <auto-generated />
using DiyabOcean.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiyabOcean.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220614234308_ProductSeeding2")]
    partial class ProductSeeding2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DiyabOcean.Shared.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Finely sliced onion smothered in a simple, fragrantly spiced batter and fried to crispy perfection",
                            ImageURL = "https://www.kitchensanctuary.com/wp-content/uploads/2021/01/Onion-Bhaji-tall-FS-40.webp",
                            Name = "Onion Bhajee",
                            Price = 2.80m
                        },
                        new
                        {
                            ID = 2,
                            Description = "Aromatic golden chicken pieces in an incredible creamy curry sauce",
                            ImageURL = "https://cafedelites.com/wp-content/uploads/2019/01/Butter-Chicken-IMAGE-27.jpg",
                            Name = "Butter Chicken",
                            Price = 8.45m
                        },
                        new
                        {
                            ID = 3,
                            Description = "Soft fluffy naan bread, brushed with melted garlic butter.",
                            ImageURL = "https://www.kitchensanctuary.com/wp-content/uploads/2021/03/Garlic-Naan-tall-FS-27.webp",
                            Name = "Garlic Naan",
                            Price = 2.70m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
