// <auto-generated />
using DiyabOcean.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiyabOcean.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240123152336_ProductVariants")]
    partial class ProductVariants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DiyabOcean.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Starters",
                            Url = "starters"
                        });
                });

            modelBuilder.Entity("DiyabOcean.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Chaat, a traditional savoury snack sold by street vendors in India. A great starter or side dish served with home made puri.",
                            ImageUrl = "",
                            Title = "Chaat"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tender & flavorful Chilli Chicken, made with chicken marinated in soy sauce, fried till crispy, sautéed with onions, peppers & sauces.",
                            ImageUrl = "",
                            Title = "Chilli Chicken"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Spicy grilled chicken wings are everyone's favorite. Juicy chicken wings are marinated in hot sauce and grilled to perfection.",
                            ImageUrl = "",
                            Title = "Spicy Chicken Wings"
                        });
                });

            modelBuilder.Entity("DiyabOcean.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "VariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            VariantId = 2,
                            OriginalPrice = 0m,
                            Price = 3.45m
                        },
                        new
                        {
                            ProductId = 1,
                            VariantId = 3,
                            OriginalPrice = 0m,
                            Price = 3.95m
                        },
                        new
                        {
                            ProductId = 2,
                            VariantId = 1,
                            OriginalPrice = 0m,
                            Price = 3.95m
                        },
                        new
                        {
                            ProductId = 3,
                            VariantId = 1,
                            OriginalPrice = 0m,
                            Price = 3.95m
                        });
                });

            modelBuilder.Entity("DiyabOcean.Shared.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Variants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lamb"
                        });
                });

            modelBuilder.Entity("DiyabOcean.Shared.Product", b =>
                {
                    b.HasOne("DiyabOcean.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DiyabOcean.Shared.ProductVariant", b =>
                {
                    b.HasOne("DiyabOcean.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyabOcean.Shared.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("DiyabOcean.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
